/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SemesterSemesterIdRouteImport } from './routes/semester.$semesterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterSemesterIdRoute = SemesterSemesterIdRouteImport.update({
  id: '/semester/$semesterId',
  path: '/semester/$semesterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/semester/$semesterId': typeof SemesterSemesterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/semester/$semesterId': typeof SemesterSemesterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/semester/$semesterId': typeof SemesterSemesterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/semester/$semesterId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/semester/$semesterId'
  id: '__root__' | '/' | '/semester/$semesterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SemesterSemesterIdRoute: typeof SemesterSemesterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester/$semesterId': {
      id: '/semester/$semesterId'
      path: '/semester/$semesterId'
      fullPath: '/semester/$semesterId'
      preLoaderRoute: typeof SemesterSemesterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SemesterSemesterIdRoute: SemesterSemesterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
